INTEG-238: create refresh, access token and redirect url
plug-and-pay/sdk-php pull request #58
Opened 2024-08-29 06:27 UTC by JoeyDeHaas

- [ ] Client mocking
- [ ] Unit tests
- [ ] Method for refreshing access token
- [ ] Method for getting access token
- [ ] Method for creating redirect url

2024-09-02 08:05 UTC, reindert-vetter requested changes
Ziet er goed uit!

- [ ] even testen in een playground

+ als ik je kan helpen met die tests, moet het zeggen

2024-09-05 09:58 UTC, reindert-vetter approved these changes
Even je checkboxes afwerken, maar een dikke: ✔️

2024-09-05 09:58 UTC, reindert-vetter commented on src/Service/TokenService.php
> +        return !($currentTime >= $expirationTime || ($expirationTime - $currentTime) < self::MIN_TTL_SECONDS);
```suggestion
        return !(($currentTime + self::MIN_TTL_SECONDS) >= $expirationTime);
```
Kan dit ook? Vind je dit duidelijker?

2024-09-05 12:06 UTC, JoeyDeHaas commented on src/Service/TokenService.php
> +        return !($currentTime >= $expirationTime || ($expirationTime - $currentTime) < self::MIN_TTL_SECONDS);
nice!

2024-09-06 11:19 UTC, reindert-vetter approved these changes
Dit is echt nice!

2024-09-06 11:24 UTC, merged